#include "BTree.h"

#ifndef TASK1_H
#define TASK1_H

/**
 *
 * @param infix_exp Is the string which the user inputs and would be converted to postfix expression
 * @return A string in postfix form
 */
std::string infix_to_postfix(std::string infix_exp);

/**
 *
 * @param postfix It is the expression in postfix which we want to parse using postfix_to_parse_tree function
 * @return The root of the BTree generated by the function
 */
BTree *postfix_to_parse_tree(std::string *postfix);

/**
 *
 * @param root It is the root of the parse tree which we want to convert to infix form
 * @return A string containing the original infix expression through which the parse tree was generated
 */
std::string parse_tree_to_infix(BTree *root);

#endif
